name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        include:
          - mediawiki_version: '1.35'
            smw_version: '4.2.0'    # SemanticMediaWiki
            php_version: 7.4        # PHP
            dt_version: 3.1         # DisplayTitle
            ps_version: 0.6.1       # PageSchemas
            database_type: mysql
            database_image: "mysql:5.7"
            coverage: true
            experimental: false
          - mediawiki_version: '1.35'
            smw_version: '4.2.0'
            php_version: 7.4
            dt_version: 3.1
            ps_version: 0.6.1
            database_type: sqlite
            coverage: false
            experimental: false
          - mediawiki_version: '1.39'
            smw_version: '4.2.0'
            php_version: 8.1
            dt_version: 4.0.2
            ps_version: 0.9.1
            database_type: mysql
            database_image: "mysql:8"
            coverage: false
            experimental: true
          - mediawiki_version: '1.40'
            smw_version: dev-master
            php_version: 8.1
            dt_version: 4.0.2
            ps_version: 0.8
            database_type: mysql
            database_image: "mysql:8"
            coverage: false
            experimental: true

    env:
      MW_VERSION: ${{ matrix.mediawiki_version }}
      SMW_VERSION: ${{ matrix.smw_version }}
      PHP_VERSION: ${{ matrix.php_version }}
      DT_VERSION: ${{ matrix.dt_version }}
      PS_VERSION: ${{ matrix.ps_version }}
      DB_TYPE: ${{ matrix.database_type }}
      DB_IMAGE: ${{ matrix.database_image }}

      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
                   
      - name: Update submodules
        run: git submodule update --init --remote
  
      - name: Run tests
        run: make ci
        if: matrix.coverage == false

      - name: Run tests with coverage
        run: make ci-coverage
        if: matrix.coverage == true

      - name: Upload code coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/php/coverage.xml
        if: matrix.coverage == true
